#+TITLE: Modifyting Reverse Proxy on Open edX platform for altering content.
#+AUTHOR: VLEAD
#+DATE: [2017-11-27 Mon]
#+SETUPFILE: ./org-templates/level-0.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction
  This document lists steps to alter the content before it
  is served by Open edX.

* Create HTML and JS
  Insert JS code in an html file to remove the header and
  footer of a default Open edX page.  The file
  =alter-content.html= is created at location
  =/edx/var/nginx/server-static/=
  
  The contents of this file are below.

  #+BEGIN_EXAMPLE
   <html>
     <head>
       <script>
         var delHeader = function() {
         headerElem = document.getElementById('global-navigation')
         headerElem.parentNode.removeChild(headerElem)
         };

         var delFooter = function() {
         var elements = document.getElementsByClassName('wrapper-footer');
         while(elements.length > 0) {
           elements[0].parentNode.removeChild(elements[0]);
         }
         };

         var delHeaderAndFooter = function() {
         delHeader();
         delFooter();
         };


       </script>
     </head>
     <body onload="delHeaderAndFooter();">
     </body>
   </html>
  #+END_EXAMPLE

* Configure nginx reverse proxy
  Reverse proxy on Open edX platform is configured to add
  the file =alter-content.html= to every response.  Add the
  below line to the directive =location @proxy_to_lms_app=
  in the file =/etc/nginx/sites-enabled/lms=
  #+BEGIN_EXAMPLE
   location @proxy_to_lms_app {
    add_after_body /server/alter-content.html;
    ------
    ------

   }
  #+END_EXAMPLE

* Restart the services
  Restart services on Open edX to pick the new configuration
  changes.
  #+BEGIN_EXAMPLE
  /edx/bin/supervisorctl restart edxapp:
  #+END_EXAMPLE
* Configure x-frame options
  - By default =x-frame= http response header of pages
    served from OpenEdx are set to =DENY= for security
    reasons. To enable loading all these pages inside
    iframes this is to be set to =ALLOW=.
  - To enable this feature change =x_frame_option= value
    from =DENY= to =ALLOW= in
    =/edx/app/edxapp/edx-platform/common/djangoapps/third_party_auth/decorators.py=
    #+BEGIN_EXAMPLE
    #x_frame_option = 'DENY'
    x_frame_option = 'ALLOW'
    #+END_EXAMPLE
* Configure post message
  Following code snippet is to be configured in =openedx=
  server. This is required to send the post messages to
  destination server. Place the following snippet inside
  =/edx/var/nginx/server-static/message.html=
#+BEGIN_SRC html
<html>
  <head>
    <script>
      var postM = function() {
      textOfContentIframe = document.body.innerText;
      console.log("Sender message: " + textOfContentIframe);
      //console.log("Referrer: " + document.referrer);
      msg = window.parent.postMessage(textOfContentIframe, "http://header.vlabs.ac.in");
      };
    </script>
  </head>
  <body onload="postM();">
  </body>
</html>
#+END_SRC
In above code snippet =http://header.vlabs.ac.in= is the
server name where all post messages will be sent. Configure
the =nginx= server file in =/etc/nginx/sites-enabled/lms= to
sent post messages script
#+BEGIN_EXAMPLE
location @proxy_to_lms_app {
   add_after_body /server/message.html;
   --------------
   -------------
#+END_EXAMPLE
* Delete header and footer
  To disable =header= and =footer= pages from openedx
  comment out below lines from file
  =/edx/app/edxapp/edx-platform/lms/templates/main.html=
  #+BEGIN_EXAMPLE
  ##<%static:optional_include_mako file="body-initial.html" is_theming_enabled="True" />
  ## % if not disable_header:
  ##   <%include file="${static.get_template_path('header.html')}" args="online_help_token=online_help_token" />
  ## <%include file="/preview_menu.html" />
  ##% endif

  ##  % if not disable_footer:
  ##    <%include file="${static.get_template_path('footer.html')}" />
  ##% endif
  #+END_EXAMPLE
