#+TITLE: Disciplines
#+AUTHOR: VLEAD
#+DATE: <2017-04-06 Thu>
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction
  This has functionality for all the operations related to
  =Discipline= 
* Disciplines
** Load all disciplines
   This function loads all the disciplines into an iframe.
   Before loading it removes existing iframe and creates new
   one.
#+NAME: load-all-disciplines
#+BEGIN_SRC javascript 
var loadAllDisciplines = function() {
  console.log("=======loading all disciplines=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "1180em");
  insertFrameInDivision(newFrame, "contentDiv");
  getAllDisciplines();
};

#+END_SRC

** Get All Disciplines
   All the disciplines from the =LDS= are collected along
   with images, hyperlinks.  This data is formatted and
   events are attached.  A div element is created containing
   this data.  The events attached are =onclick= and the
   handler loads the labs associated with the discipline.
   This event =onclick= is attached for both the image and
   name of the discipline.  Once the content is created,
   there is a call to insert this content in an iframe.
#+NAME: get-all-disciplines
#+BEGIN_SRC javascript 
var getAllDisciplines = function(){ 
  console.log("=========inside get all disciplines==========");
  var dis_url = lds_url + "/disciplines";
//  console.log(dis_url);
  $.getJSON(dis_url, function(data) {
    var disciplines = '';
    data.sort(function (key, value) {
      return key.discipline_name.localeCompare(value.discipline_name);
    });
    $.each(data, function(key, value){
    var discipline_name = value['discipline_name'];
    var image_name = value['assets'][0]['path'];
    var image_path = discipline_images_url + image_name;
     disciplines += '<div class="col-lg-3 col-md-4 col-xs-12 thumb"  \
 onclick="getLabsByDisciplineName(this, 0)" src="'
    + image_path +'" id="' + discipline_name + '"> <div class="thumbnail"  \
style="cursor: pointer; padding: 0px !important; padding-top:15px !important;"> <a><img class="img-responsive" onclick="getLabsByDisciplineName(this, 0)" src="'
    + image_path +'" id="' + discipline_name + '"style="cursor: pointer;"> \
<div class="caption" style="min-height: 110px;">\
<h4 onclick="getLabsByDisciplineName(this, 0)"  src="' + image_path +'" id="' + discipline_name +
      '" style="text-align:center; color:#2c99ce;" >'+ discipline_name +'</h4></a></div></div></div>';
    });
    var discipline_list = '<div class="container-fluid"><div class="row">'
    + disciplines +'</div></div>';
    setContent(discipline_list, "disciplines.html");
    })
    .done(function() {
      console.log( "second success" );
    })
    .fail(function() {
      console.log( "error" );
    })
    .always(function() {
      console.log( "complete" );
    });
    };
    
#+END_SRC
** Get Labs by Discipline Name
   This function gets the labs of respective discipline
   based on the value of =click= event occurs on discipline
   name.

#+NAME: get-labs-by-discipline-name
#+BEGIN_SRC javascript 
var getLabsByDisciplineName = function(image, flag) {
  console.log("===========inside getLabsByDisciplineName==========");

  if (flag == 1){
    deleteFrameInDivision("contentIframe", "contentDiv");
    var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "650em");
    insertFrameInDivision(newFrame, "contentDiv");
  }
  var discipline_name = image.id;
  var labs_url = lds_url + "/labs";
  var labs_by_dis_url = labs_url + "?discipline_name="+ discipline_name;
  $.getJSON(labs_by_dis_url, function(data) {
    var labs = '';
    data.sort(function (key, value) {
      return key.lab_name.localeCompare(value.lab_name);
    });
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
          hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
      for(var i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
          path = lab_images_url + image_name;
        }
      }

      labs += '<div class=" col-md-3 " id='+ lab_name +
           '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
      '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';
   });
    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    resetContentInIframe(labs, "labs.html");
  })
    .done(function() {
     console.log( "second success" );
    })
    .fail(function() {
     console.log( "error" );
      location.reload();
    })
    .always(function() {
     console.log( "complete" );
    });
};

#+END_SRC
** Get All Disciplines in drop down menu
   This function does the following
   1. Gets all the disciplines in drop down menu
   2. Display all the labs into =contentIframe= of chosen
      discipline from drop down menu
#+NAME: get-all-disciplines-in-combobox
#+BEGIN_SRC javascript
var getAllDisciplinesInCombobox = function(){
  console.log("=========inside get all disciplines in combobox==========");
  var discipline_url = lds_url + "/disciplines";
  $.getJSON(discipline_url, function(data) {
    var disciplines = '';
    data.sort(function (key, value) {
      return key.discipline_name.localeCompare(value.discipline_name);
    });
    $.each(data, function(key, value){
    var discipline_name = value['discipline_name'];
      disciplines += '<li onclick="getLabsByDisciplineName(this, 1)" value="'
        + discipline_name + '" id="' + discipline_name + '"><a >' +
        discipline_name + '</a></li>';
    });
    var discipline_list = '<li onclick="loadAllDisciplines()">\
<a>All Disciplines</a></li>' + disciplines;
//    console.log(discipline_list);
    $('.filterDisciplineComboBox').append(discipline_list);

    })
    .done(function() {
//    console.log( "second success" );
    })
    .fail(function() {
//    console.log( "error" );
    })
    .always(function() {
//    console.log( "complete" );
    });
    };

#+END_SRC
* Tangle 
** sources
*** Javascript
**** Main JS
#+BEGIN_SRC javascript :tangle js/disciplines.js :eval no :noweb yes 
<<get-labs-by-discipline-name>>
<<get-all-disciplines-in-combobox>>
<<load-all-disciplines>>
<<get-all-disciplines>>
#+END_SRC
