#+TITLE: Runtime
#+AUTHOR: VLEAD
#+DATE: [2017-04-06 Thursday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This "Literate Document" is an illustration of building
  =Vlabs landing Pages=. It includes updating the data in
  the web page, using =Lab Data Service=. This helps us
  achieve a lot of tasks, Some of them are mentioned below
  - It explains the approach to access the data of labs that
    are segregated based on institutes.
  - It explains the approach to access the data of labs that
    are segregated based on disciplines.
  - Accessing all the data of labs.

* Implementation
** Index page on load 
   Every page has a controller, content and footer.  Both
   the content and the footer are served from iframes.  The
   content is either:
   1. list of disciplines
   2. list of institutes
   3. list of labs which can either be:
      1. labs of a discipline
      2. labs of an institute or
      3. all labs
      or
   4. the lab itself. 

   On the initial load,  the content lists all the
   disciplines.  

#+NAME: load-index
#+BEGIN_SRC js
var labs_data = null;
var labs_data_db = null;
var loadIndex = function() {
  console.log("=======loading index page=====");
  getAllInstitutesInCombobox(); 
  getAllDisciplinesInCombobox(); 
  on_mouse_hover();
  getWorkshopUsage();
  getTotalUsage();
  insertContentIFrame();
  if (labs_data == null)
  {
    getAllLabs();
  }
  loadAllDisciplines();
  insertFooterIFrame();
  setFooterContentInIframe();
};

#+END_SRC
** Add Script Tags 
   Script tags are created dynamically and appended to the
   =<head>= tag.

#+NAME: add-script-tags
#+BEGIN_SRC javascript 
var addScriptTags = function(){
  var contentIframe = parent.document.getElementById("contentIframe");
  
  var js_script = contentIframe.contentWindow.document.createElement("script");
  var js_url = "./js/main.js";
  js_script.type = "text/javascript";
  js_script.src = js_url;
  var head = contentIframe.contentWindow.document.head;
  head.appendChild(js_script);

  var auth_js_script = contentIframe.contentWindow.document.createElement("script");
  var auth_js_url = "./js/auth.js";
  auth_js_script.type = "text/javascript";
  auth_js_script.src = auth_js_url;
  head.appendChild(auth_js_script);

  var manage_iframes_js_script = contentIframe.contentWindow.document.createElement("script");
  var manage_iframes_js_url = "./js/manage_iframes.js";
  manage_iframes_js_script.type = "text/javascript";
  manage_iframes_js_script.src = manage_iframes_js_url;
  head.appendChild(manage_iframes_js_script);

  var search_js_script = contentIframe.contentWindow.document.createElement("script");
  var search_js_url = "./js/search.js";
  search_js_script.type = "text/javascript";
  search_js_script.src = search_js_url;
  head.appendChild(search_js_script);
  
  var disciplines_js_script = contentIframe.contentWindow.document.createElement("script");
  var disciplines_js_url = "./js/disciplines.js";
  disciplines_js_script.type = "text/javascript";
  disciplines_js_script.src = disciplines_js_url;
  head.appendChild(disciplines_js_script);

  var institutes_js_script = contentIframe.contentWindow.document.createElement("script");
  var institutes_js_url = "./js/institutes.js";
  institutes_js_script.type = "text/javascript";
  institutes_js_script.src = institutes_js_url;
  head.appendChild(institutes_js_script);
  
  var usage_script = contentIframe.contentWindow.document.createElement("script");
  var usage_url = "./js/usage.js";
  usage_script.type = "text/javascript";
  usage_script.src = usage_url;
  head.appendChild(usage_script);

  var config_script = contentIframe.contentWindow.document.createElement("script");
  var config_url = "./js/app-config.js";
  config_script.type = "text/javascript";
  config_script.src = config_url;
  head.appendChild(config_script);
  
  var jquery_script = contentIframe.contentWindow.document.createElement("script");
  var jquery_url = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js";
  jquery_script.type = "text/javascript";
  jquery_script.src = jquery_url;
  head.appendChild(jquery_script);  

  var styles = contentIframe.contentWindow.document.createElement("link");
  var css_url = "./css/style.css";
  styles.type = "text/stylesheet";
  styles.href = css_url;
  head.appendChild(styles);

  var bootstrap_styles = contentIframe.contentWindow.document.createElement("link");
  var bootstrap_css_url = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css";
  bootstrap_styles.rel = "stylesheet";
  bootstrap_styles.href = bootstrap_css_url;
  head.appendChild(bootstrap_styles);

  var favicon = contentIframe.contentWindow.document.createElement("link");
  var favicon_url = "";
  favicon.type = "image/x-icon";
  favicon.href = favicon_url;
  head.appendChild(favicon);

};

#+END_SRC

** Mouse Over
   This function allows the dropdown menu on the mousehover
   event.
#+NAME: mouse-over
#+BEGIN_SRC javascript
var on_mouse_hover = function(){
$(".dropdown").hover(            
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("400");
    $(this).toggleClass('open');        
  },
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("400");
    $(this).toggleClass('open');       
  }
);
};
#+END_SRC

** Favicon
   =Favicon= image is dynamically created and appended to
   the =<head>= tag.
#+NAME: favicon
#+BEGIN_SRC javascript 
master = window.parent.document;
head = master.getElementsByTagName("head")[0];
favicon = master.createElement("link");
favicon.rel = "shortcut icon";
favicon.type = "image/png";
favicon.href = "http://files.vlabs.ac.in/lds/images/vlabs-logo/favicon.ico";
head.appendChild(favicon);

#+END_SRC

* Tangle 
** sources
*** Javascript
**** Main JS
#+BEGIN_SRC javascript :tangle js/main.js :eval no :noweb yes 
<<load-index>>
<<add-script-tags>>
<<mouse-over>>
#+END_SRC

