#+TITLE: Runtime
#+AUTHOR: VLEAD
#+DATE: [2017-04-06 Thursday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This "Literate Document" is an illustration of building
  =Vlabs landing Pages=. It includes updating the data in
  the web page, using =Lab Data Service=. This helps us
  achieve a lot of tasks, Some of them are mentioned below
  - It explains the approach to access the data of labs that
    are segregated based on institutes.
  - It explains the approach to access the data of labs that
    are segregated based on disciplines.
  - Accessing all the data of labs.

* Implementation
** Index page on load 
   An index initially loads with a header, discipline
   content and footer set the content in respective iframe
   by invoking, =setContentInIframe()=,
   =setFooterContentInIframe()= functions. This function
   also makes a parallel request to get the labs and updates
   the global variable =labs_data=.

#+NAME: load-index
#+BEGIN_SRC js
var labs_data = null;
var labs_data_db = null;
var loadIndex = function() {
  console.log("=======loading index page=====");
  getAllInstitutesInCombobox(); 
  getAllDisciplinesInCombobox(); 
  on_mouse_hover();
  getWorkshopUsage();
  getTotalUsage();
  insertContentIFrame();
  if (labs_data == null)
  {
    getAllLabs();
  }
  loadAllDisciplines();
  insertFooterIFrame();
  setFooterContentInIframe();
};

#+END_SRC
** Loading all labs
   This allows to manipulate the content of an iframe by
   invoking =getAllLabs()= function and set the obtained
   labs by invoking =setContentInIframe()= in the content
   iframe.
#+NAME: load-all-labs
#+BEGIN_SRC javascript 
var loadAllLabs = function() {
  console.log("=======loading all labs=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "9500em");
  insertFrameInDivision(newFrame, "contentDiv");
  var labs = getAllLabs();
  setLabDataInIframe();
};

#+END_SRC

** Set usage in Iframe
   This allows to manipulate usage data in the content
   iframe. The usage data will be set in the content iframe
   immediately.
#+NAME: set-usage-in-iframe
#+BEGIN_SRC javascript 
var setUsageInIframe = function() {
  console.log("=======setting usage to content iframe=====");        
  var iframe = parent.document.getElementById("contentIframe");
  iframe.src = "https://info.vlabs.ac.in/analytics/analytics/usage.html";
};

#+END_SRC
** Get All Labs
   This function will be invoked when =All Labs= tab is
   clicked. It invokes a call to =LDS= database and fetches
   all the labs info and calls =setNewContentInIframe()=
   function to display the data in an iframe. Also calls
   =addScriptTags()= function to append =main.js=, =jquery=
   and =app-config= to =<head>= tag as =<script>=.   
#+NAME: get-all-labs
#+BEGIN_SRC  javascript 
var getAllLabs = function(){ 
  console.log("=========inside get all labs==========");
  var lab_url = lds_url+"/labs";
//  console.log(lab_url);
  $.getJSON(lab_url, function(data) {
    var labs = '';
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
           hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
//      console.log(assets);
      for(i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
//          console.log(image_name);
           path = lab_images_url + image_name;
//          console.log(path);
        }
      }
      labs += '<div class=" col-md-3 " id='+ lab_name +
        '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
        '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';
    });
//    console.log(labs);
    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    labs_data = labs_list;
//    console.log(labs_data);
    labs_data_db = data;
    var all_labs_element = document.getElementById("allLabs");
    all_labs_element.classList.remove("disabled");
    var search_element = document.getElementById("search");
    search_element.classList.remove("disabled");
    addScriptTags();
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

 #+END_SRC
** Get Lab
#+NAME: get-lab
#+BEGIN_SRC javascript
var getLab = function(url){
    validateAuthentication(url);
    //hosted_url = url.id;    
    //var iframe = parent.document.getElementById("contentIframe");
    //iframe.src = hosted_url;
    addScriptTags();
};

#+END_SRC
** Add Script Tags 
   Script tags are created dynamically and appended to the
   =<head>= tag.

#+NAME: add-script-tags
#+BEGIN_SRC javascript 
var addScriptTags = function(){
  var contentIframe = parent.document.getElementById("contentIframe");
  
  var js_script = contentIframe.contentWindow.document.createElement("script");
  var js_url = "./js/main.js";
  js_script.type = "text/javascript";
  js_script.src = js_url;
  var head = contentIframe.contentWindow.document.head;
  head.appendChild(js_script);

  var auth_js_script = contentIframe.contentWindow.document.createElement("script");
  var auth_js_url = "./js/auth.js";
  auth_js_script.type = "text/javascript";
  auth_js_script.src = auth_js_url;
  head.appendChild(auth_js_script);

  var manage_iframes_js_script = contentIframe.contentWindow.document.createElement("script");
  var manage_iframes_js_url = "./js/manage_iframes.js";
  manage_iframes_js_script.type = "text/javascript";
  manage_iframes_js_script.src = manage_iframes_js_url;
  head.appendChild(manage_iframes_js_script);

  var search_js_script = contentIframe.contentWindow.document.createElement("script");
  var search_js_url = "./js/search.js";
  search_js_script.type = "text/javascript";
  search_js_script.src = search_js_url;
  head.appendChild(search_js_script);
  
  var disciplines_js_script = contentIframe.contentWindow.document.createElement("script");
  var disciplines_js_url = "./js/disciplines.js";
  disciplines_js_script.type = "text/javascript";
  disciplines_js_script.src = disciplines_js_url;
  head.appendChild(disciplines_js_script);

  var institutes_js_script = contentIframe.contentWindow.document.createElement("script");
  var institutes_js_url = "./js/institutes.js";
  institutes_js_script.type = "text/javascript";
  institutes_js_script.src = institutes_js_url;
  head.appendChild(institutes_js_script);
  
  var config_script = contentIframe.contentWindow.document.createElement("script");
  var config_url = "./js/app-config.js";
  config_script.type = "text/javascript";
  config_script.src = config_url;
  head.appendChild(config_script);
  
  var jquery_script = contentIframe.contentWindow.document.createElement("script");
  var jquery_url = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js";
  jquery_script.type = "text/javascript";
  jquery_script.src = jquery_url;
  head.appendChild(jquery_script);  

  var styles = contentIframe.contentWindow.document.createElement("link");
  var css_url = "./css/style.css";
  styles.type = "text/stylesheet";
  styles.href = css_url;
  head.appendChild(styles);

  var bootstrap_styles = contentIframe.contentWindow.document.createElement("link");
  var bootstrap_css_url = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css";
  bootstrap_styles.rel = "stylesheet";
  bootstrap_styles.href = bootstrap_css_url;
  head.appendChild(bootstrap_styles);

  var favicon = contentIframe.contentWindow.document.createElement("link");
  var favicon_url = "";
  favicon.type = "image/x-icon";
  favicon.href = favicon_url;
  head.appendChild(favicon);

};

#+END_SRC

** Resetting content in Iframe
   Resetting the content in the same frame is just element
   manipulation where =contentIframe= is accessed and new
   content is set.
#+NAME: reset-content
#+BEGIN_SRC javascript 
var resetContentInIframe = function(data) {
  console.log("=======re setting content=====");        
//  console.log(data);
  var iframe = parent.document.getElementById("contentIframe");
  iframe.sandbox = 'allow-scripts allow-same-origin allow-popups allow-forms';
  var content = iframe.contentWindow.document;
//  console.log(content);
  content.body.innerHTML="";
  content.write(data);
  addScriptTags();

};

#+END_SRC

** Back button
#+NAME: back-button
#+BEGIN_SRC javascript 
/*bajb_backdetect.OnBack = function()
{
alert('You clicked it!');
}*/
#+END_SRC
** Get Workshop Usage Data 
   This function dynamically fetches the usage data.
#+NAME: workshop-usage-data
#+BEGIN_SRC javascript
var getWorkshopUsage = function(){ 
$.getJSON(workshop_usage_url, function(data) {
  var usage = data["usage"];
  $("#usage").html(usage);
})
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};
#+END_SRC
** Total usage data 
   This function dynamically fetches the total usage data.
#+NAME: total-usage-data
#+BEGIN_SRC javascript
var getTotalUsage = function() {
$.getJSON(total_usage_url, function(data) {
  var usage = data["usage"];
  $("#totalusage").html(usage);
})
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};
#+END_SRC
** Mouse Over
   This function allows the dropdown menu on the mousehover
   event.
#+NAME: mouse-over
#+BEGIN_SRC javascript
var on_mouse_hover = function(){
$(".dropdown").hover(            
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("400");
    $(this).toggleClass('open');        
  },
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("400");
    $(this).toggleClass('open');       
  }
);
};
#+END_SRC

** Favicon
#+NAME: favicon
#+BEGIN_SRC javascript 
master = window.parent.document;
head = master.getElementsByTagName("head")[0];
favicon = master.createElement("link");
favicon.rel = "shortcut icon";
favicon.type = "image/png";
favicon.href = "http://files.vlabs.ac.in/lds/images/vlabs-logo/favicon.ico";
head.appendChild(favicon);

#+END_SRC

* Tangle 
** sources
*** Javascript
**** Main JS
#+BEGIN_SRC javascript :tangle js/main.js :eval no :noweb yes 
<<post-message-event-listner>>
<<load-index>>
<<reset-content>>
<<add-script-tags>>
<<set-register-url-to-content-iframe>>
<<set-login-url-to-content-iframe>>
<<validate-authentication>>
<<set-usage-in-iframe>>
<<load-all-labs>>
<<get-all-labs>>
<<mouse-over>>
<<back-button>>
<<workshop-usage-data>>
<<total-usage-data>>
<<validate-cookie>>
<<validate-post-message>>
#+END_SRC

