#+TITLE: Runtime
#+AUTHOR: VLEAD
#+DATE: [2017-04-06 Thursday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This "Literate Document" is an illustration of building
  =Vlabs landing Pages=. It includes updating the data in
  the web page, using =Lab Data Service=. This helps us
  achieve a lot of tasks, Some of them are mentioned below
  - It explains the approach to access the data of labs that
    are segregated based on institutes.
  - It explains the approach to access the data of labs that
    are segregated based on disciplines.
  - Accessing all the data of labs.

* Implementation
** Index page on load 
   An index initially loads with a header, discipline
   content and footer set the content in respective iframe
   by invoking, =setContentInIframe()=,
   =setFooterContentInIframe()= functions. This function
   also makes a parallel request to get the labs and updates
   the global variable =labs_data=.

#+NAME: load-index
#+BEGIN_SRC js
var labs_data = null;
var labs_data_db = null;
var loadIndex = function() {
  console.log("=======loading index page=====");
  getAllInstitutesInCombobox(); 
  getAllDisciplinesInCombobox(); 
  on_mouse_hover();
  getWorkshopUsage();
  getTotalUsage();
  insertContentIFrame();
  if (labs_data == null)
  {
    getAllLabs();
  }
  loadAllDisciplines();
  insertFooterIFrame();
  setFooterContentInIframe();
};

#+END_SRC
** Loading all disciplines
   This allows to manipulate the content of an iframe by
   invoking =getAllDisciplines()= function and set the
   obtained disciplines by invoking =setContentInIframe()=
   in the content iframe.
#+NAME: load-all-disciplines
#+BEGIN_SRC javascript 
var loadAllDisciplines = function() {
  console.log("=======loading all disciplines=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "1180em");
  insertFrameInDivision(newFrame, "contentDiv");
  getAllDisciplines();
};

#+END_SRC

** Loading all institutes
   This allows to manipulate the content of an iframe by
   invoking =getAllInstitutes()= function and set the
   obtained institutes by invoking =setContentInIframe()= in
   the content iframe.

#+NAME:load-all-institutes
#+BEGIN_SRC javascript 
var loadAllInstitutes = function() {
  console.log("=======loading all institutes=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "790em");
  insertFrameInDivision(newFrame, "contentDiv");
  getAllInstitutes();
};

#+END_SRC

** Loading all labs
   This allows to manipulate the content of an iframe by
   invoking =getAllLabs()= function and set the obtained
   labs by invoking =setContentInIframe()= in the content
   iframe.
#+NAME: load-all-labs
#+BEGIN_SRC javascript 
var loadAllLabs = function() {
  console.log("=======loading all labs=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "9500em");
  insertFrameInDivision(newFrame, "contentDiv");
  var labs = getAllLabs();
  setLabDataInIframe();
};

#+END_SRC

** Set usage in Iframe
   This allows to manipulate usage data in the content
   iframe. The usage data will be set in the content iframe
   immediately.
#+NAME: set-usage-in-iframe
#+BEGIN_SRC javascript 
var setUsageInIframe = function() {
  console.log("=======setting usage to content iframe=====");        
  var iframe = parent.document.getElementById("contentIframe");
  iframe.src = "https://info.vlabs.ac.in/analytics/analytics/usage.html";
};

#+END_SRC
** Get All Institutes
   This function will be invoked when =All Institutes= tab
   is clicked. It invokes a call to =LDS= database and
   fetches all the institutes info and calls
   =setNewContentInIframe()= function to display the data in
   an iframe. Also calls =addScriptTags()= function to
   append =main.js=, =jquery= and =app-config= to =<head>=
   tag as =<script>=.

#+NAME: get-all-institutes
#+BEGIN_SRC javascript 
var getAllInstitutes = function(){ 
  console.log("=========inside get all institutes==========");
  var institute_url = lds_url+"/institutes";
//  console.log(institute_url);
  $.getJSON(institute_url, function(data) {
    var institutes = '';
    $.each(data, function(key, value){
      var institute_name = value['institute_name'];
      var image_name = value['assets'][0]['path'];
      var image_path = institute_images_url + image_name;

institutes += '<div class="col-lg-3 col-md-4 col-xs-12 thumb" \
 onclick="getLabsByInstituteName(this, 0)" src="' + image_path +'" id="' + institute_name +
      '"><div class="thumbnail" \
style="cursor:pointer; padding: 0px !important; padding-top:15px \
!important;"> <a><img class="img-responsive " \
onclick="getLabsByInstituteName(this, 0)" src="' + image_path +'" id="' + institute_name +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="getLabsByInstituteName(this, 0)"  src="' + image_path +'" id="' + institute_name +
      '" style="text-align:center; color:#2c99ce;" >'+ institute_name +'</h4></a></div></div></div>';
          });

    var institute_list = '<div class="container-fluid"><div class="row">'
        + institutes +'</div></div>';
//    console.log(institutes);
    setNewContentInIframe(institute_list);
    addScriptTags();
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC
** Get All Disciplines
   This function will be invoked when =All Disciplines= tab
   is clicked. It invokes a call to =LDS= database and
   fetches all the disciplines info and calls
   =setNewContentInIframe()= function to display the data in
   an iframe. Also calls =addScriptTags()= function to
   append =main.js=, =jquery= and =app-config= to =<head>=
   tag as =<script>=.
#+NAME: get-all-disciplines
#+BEGIN_SRC javascript 
var getAllDisciplines = function(){ 
  console.log("=========inside get all disciplines==========");
  var dis_url = lds_url+"/disciplines";
//  console.log(dis_url);
  $.getJSON(dis_url, function(data) {
    var disciplines = '';
    $.each(data, function(key, value){
    var discipline_name = value['discipline_name'];
    var image_name = value['assets'][0]['path'];
    var image_path = discipline_images_url + image_name;
     disciplines += '<div class="col-lg-3 col-md-4 col-xs-12 thumb"  \
 onclick="getLabsByDisciplineName(this, 0)" src="'
    + image_path +'" id="' + discipline_name + '"> <div class="thumbnail"  \
style="cursor: pointer; padding: 0px !important; padding-top:15px !important;"> <a><img class="img-responsive" onclick="getLabsByDisciplineName(this, 0)" src="'
    + image_path +'" id="' + discipline_name + '"style="cursor: pointer;"> \
<div class="caption" style="min-height: 110px;">\
<h4 onclick="getLabsByDisciplineName(this, 0)"  src="' + image_path +'" id="' + discipline_name +
      '" style="text-align:center; color:#2c99ce;" >'+ discipline_name +'</h4></a></div></div></div>';
    });
    var discipline_list = '<div class="container-fluid"><div class="row">'
    + disciplines +'</div></div>';
    
//    console.log(disciplines);
    setNewContentInIframe(discipline_list);
    addScriptTags();
    })
    .done(function() {
//    console.log( "second success" );
    })
    .fail(function() {
//    console.log( "error" );
    })
    .always(function() {
//    console.log( "complete" );
    });
    };
    
#+END_SRC
** Get All Labs
   This function will be invoked when =All Labs= tab is
   clicked. It invokes a call to =LDS= database and fetches
   all the labs info and calls =setNewContentInIframe()=
   function to display the data in an iframe. Also calls
   =addScriptTags()= function to append =main.js=, =jquery=
   and =app-config= to =<head>= tag as =<script>=.   
#+NAME: get-all-labs
#+BEGIN_SRC  javascript 
var getAllLabs = function(){ 
  console.log("=========inside get all labs==========");
  var lab_url = lds_url+"/labs";
//  console.log(lab_url);
  $.getJSON(lab_url, function(data) {
    var labs = '';
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
           hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
//      console.log(assets);
      for(i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
//          console.log(image_name);
           path = lab_images_url + image_name;
//          console.log(path);
        }
      }
      labs += '<div class=" col-md-3 " id='+ lab_name +
        '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
        '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';
    });
//    console.log(labs);
    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    labs_data = labs_list;
//    console.log(labs_data);
    labs_data_db = data;
    var all_labs_element = document.getElementById("allLabs");
    all_labs_element.classList.remove("disabled");
    var search_element = document.getElementById("search");
    search_element.classList.remove("disabled");
    addScriptTags();
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

 #+END_SRC
** Get Lab
#+NAME: get-lab
#+BEGIN_SRC javascript
var getLab = function(url){
    validateAuthentication(url);
    //hosted_url = url.id;    
    //var iframe = parent.document.getElementById("contentIframe");
    //iframe.src = hosted_url;
    addScriptTags();
};

#+END_SRC
** Get Labs by Discipline Name
   =getAllDisciplines()= function will invokes this
   function. This function dynamically fetches the labs
   based on the 'click' event occurs on discipline
   name. This function also invokes
   =resetContentInIframe(data)= function to replace
   currently available content with the given =data=.

#+NAME: get-labs-by-discipline-name
#+BEGIN_SRC javascript 
var getLabsByDisciplineName = function(image, flag) {
  console.log("===========inside getLabsByDisciplineName==========");
 // console.log("===========flag==========");
//  console.log(flag);
  if (flag==1){
    deleteFrameInDivision("contentIframe", "contentDiv");
    var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "650em");
    insertFrameInDivision(newFrame, "contentDiv");
  }
  var discipline_name = image.id;
  var labs_url = lds_url+"/labs";
//  console.log(labs_url);
  var labs_by_dis_url = labs_url+"?discipline_name="+ discipline_name;
//  console.log(labs_by_dis_url);
  $.getJSON(labs_by_dis_url, function(data) {
    var labs = '';
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
          hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
//      console.log(assets);
      for(var i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
//          console.log(image_name);
          path = lab_images_url + image_name;
//          console.log(path);
        }
      }

      labs += '<div class=" col-md-3 " id='+ lab_name +
           '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
      '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';
   });
//    console.log(labs);
    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    resetContentInIframe(labs);
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
      location.reload();
    })
    .always(function() {
//      console.log( "complete" );
    });
  
};


#+END_SRC
** Get Labs by Institute Name
   =getAllInstitutes()= function will invokes this
   function.This function dynamically fetches the labs based
   on the 'click' event occurs on institute name.

#+NAME: get-labs-by-institute-name
#+BEGIN_SRC javascript 
var getLabsByInstituteName = function(image, flag) {
  console.log("===========inside getLabsByDisciplineName==========");
//  console.log("===========flag==========");
//  console.log(flag);
  if (flag==1){
    deleteFrameInDivision("contentIframe", "contentDiv");
    var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "650em");
    insertFrameInDivision(newFrame, "contentDiv");
  }
  var institute_name = image.id;
  var labs_url = lds_url+"/labs";
//  console.log(labs_url);
  var labs_by_institute_url = labs_url+"?institute_name="+ institute_name;
  console.log(labs_by_institute_url);
  $.getJSON(labs_by_institute_url, function(data) {
    var labs = '';
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
          hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
//      console.log(assets);
      for(var i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
  //        console.log(image_name);
          path = lab_images_url + image_name;
 //         console.log(path);
        }
      }
      labs += '<div class=" col-md-3 " id='+ lab_name +
           '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
      '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';

    });
//    console.log(labs);
    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    resetContentInIframe(labs);
  })
  .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
//      location.reload();
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC

** Get All Institutes in Combo box
   =getAllInstitutesInCombobox()= function will invokes this
   function. This function dynamically fetches the labs
   based on the 'hover' event occurs on institute which
   gives a dropdown with all institutes and each institute
   respectively.
#+NAME: get-all-institutes-in-combobox
#+BEGIN_SRC javascript
var getAllInstitutesInCombobox = function(){
  console.log("=========inside get all institutes in combobox==========");
  var institute_url = lds_url+"/institutes";
//  console.log(institute_url);
  $.getJSON(institute_url, function(data) {
    var institutes = '';
    $.each(data, function(key, value){
      var institute_name = value['institute_name'];
      institutes +=  '<li onclick="getLabsByInstituteName(this, 1)" value="'
        + institute_name + '" id="' + institute_name + '"><a >' +
        institute_name + '</a></li>';
    });
    var institute_list = '<li onclick="loadAllInstitutes()">\
<a >All Institutes</a></li>' + institutes;
//    console.log(institute_list);
    $('.filterInstituteComboBox').append(institute_list);
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC
** Get All Disciplines in Combo box
   =getAllDisciplinesInCombobox()= function will invokes
   this function. This function dynamically fetches the labs
   based on the 'hover' event occurs on discipline which
   gives a dropdown with all disciplines and each discipline
   respectively.
#+NAME: get-all-disciplines-in-combobox
#+BEGIN_SRC javascript
var getAllDisciplinesInCombobox = function(){
  console.log("=========inside get all disciplines in combobox==========");
  var discipline_url = lds_url + "/disciplines";
//  console.log(discipline_url);
  $.getJSON(discipline_url, function(data) {
    var disciplines = '';
    $.each(data, function(key, value){
    var discipline_name = value['discipline_name'];
      disciplines += '<li onclick="getLabsByDisciplineName(this, 1)" value="'
        + discipline_name + '" id="' + discipline_name + '"><a >' +
        discipline_name + '</a></li>';
    });
    var discipline_list = '<li onclick="loadAllDisciplines()">\
<a>All Disciplines</a></li>' + disciplines;
//    console.log(discipline_list);
    $('.filterDisciplineComboBox').append(discipline_list);

    })
    .done(function() {
//    console.log( "second success" );
    })
    .fail(function() {
//    console.log( "error" );
    })
    .always(function() {
//    console.log( "complete" );
    });
    };

#+END_SRC
** Add Script Tags 
   Script tags are created dynamically and appended to the
   =<head>= tag.

#+NAME: add-script-tags
#+BEGIN_SRC javascript 
var addScriptTags = function(){
  var contentIframe = parent.document.getElementById("contentIframe");
  
  var js_script = contentIframe.contentWindow.document.createElement("script");
  var js_url = "./js/main.js";
  js_script.type = "text/javascript";
  js_script.src = js_url;
  var head = contentIframe.contentWindow.document.head;
  head.appendChild(js_script);

  var auth_js_script = contentIframe.contentWindow.document.createElement("script");
  var auth_js_url = "./js/auth.js";
  auth_js_script.type = "text/javascript";
  auth_js_script.src = auth_js_url;
  head.appendChild(auth_js_script);

  var manage_iframes_js_script = contentIframe.contentWindow.document.createElement("script");
  var manage_iframes_js_url = "./js/manage_iframes.js";
  manage_iframes_js_script.type = "text/javascript";
  manage_iframes_js_script.src = manage_iframes_js_url;
  head.appendChild(manage_iframes_js_script);

  var search_js_script = contentIframe.contentWindow.document.createElement("script");
  var search_js_url = "./js/search.js";
  search_js_script.type = "text/javascript";
  search_js_script.src = search_js_url;
  head.appendChild(search_js_script);
  
  var config_script = contentIframe.contentWindow.document.createElement("script");
  var config_url = "./js/app-config.js";
  config_script.type = "text/javascript";
  config_script.src = config_url;
  head.appendChild(config_script);
  
  var jquery_script = contentIframe.contentWindow.document.createElement("script");
  var jquery_url = "https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js";
  jquery_script.type = "text/javascript";
  jquery_script.src = jquery_url;
  head.appendChild(jquery_script);  

  var styles = contentIframe.contentWindow.document.createElement("link");
  var css_url = "./css/style.css";
  styles.type = "text/stylesheet";
  styles.href = css_url;
  head.appendChild(styles);

  var bootstrap_styles = contentIframe.contentWindow.document.createElement("link");
  var bootstrap_css_url = "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css";
  bootstrap_styles.rel = "stylesheet";
  bootstrap_styles.href = bootstrap_css_url;
  head.appendChild(bootstrap_styles);

  var favicon = contentIframe.contentWindow.document.createElement("link");
  var favicon_url = "";
  favicon.type = "image/x-icon";
  favicon.href = favicon_url;
  head.appendChild(favicon);

};

#+END_SRC

** Resetting content in Iframe
   Resetting the content in the same frame is just element
   manipulation where =contentIframe= is accessed and new
   content is set.
#+NAME: reset-content
#+BEGIN_SRC javascript 
var resetContentInIframe = function(data) {
  console.log("=======re setting content=====");        
//  console.log(data);
  var iframe = parent.document.getElementById("contentIframe");
  iframe.sandbox = 'allow-scripts allow-same-origin allow-popups allow-forms';
  var content = iframe.contentWindow.document;
//  console.log(content);
  content.body.innerHTML="";
  content.write(data);
  addScriptTags();

};

#+END_SRC

** Back button
#+NAME: back-button
#+BEGIN_SRC javascript 
/*bajb_backdetect.OnBack = function()
{
alert('You clicked it!');
}*/
#+END_SRC
** Get Workshop Usage Data 
   This function dynamically fetches the usage data.
#+NAME: workshop-usage-data
#+BEGIN_SRC javascript
var getWorkshopUsage = function(){ 
$.getJSON(workshop_usage_url, function(data) {
  var usage = data["usage"];
  $("#usage").html(usage);
})
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};
#+END_SRC
** Total usage data 
   This function dynamically fetches the total usage data.
#+NAME: total-usage-data
#+BEGIN_SRC javascript
var getTotalUsage = function() {
$.getJSON(total_usage_url, function(data) {
  var usage = data["usage"];
  $("#totalusage").html(usage);
})
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};
#+END_SRC
** Mouse Over
   This function allows the dropdown menu on the mousehover
   event.
#+NAME: mouse-over
#+BEGIN_SRC javascript
var on_mouse_hover = function(){
$(".dropdown").hover(            
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideDown("400");
    $(this).toggleClass('open');        
  },
  function() {
    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true,true).slideUp("400");
    $(this).toggleClass('open');       
  }
);
};
#+END_SRC

** Favicon
#+NAME: favicon
#+BEGIN_SRC javascript 
master = window.parent.document;
head = master.getElementsByTagName("head")[0];
favicon = master.createElement("link");
favicon.rel = "shortcut icon";
favicon.type = "image/png";
favicon.href = "http://files.vlabs.ac.in/lds/images/vlabs-logo/favicon.ico";
head.appendChild(favicon);

#+END_SRC

* Tangle 
** sources
*** Javascript
**** Main JS
#+BEGIN_SRC javascript :tangle js/main.js :eval no :noweb yes 
<<post-message-event-listner>>
<<load-index>>
<<get-all-institutes-in-combobox>>
<<get-labs-by-discipline-name>>
<<get-labs-by-institute-name>>
<<reset-content>>
<<add-script-tags>>
<<set-register-url-to-content-iframe>>
<<set-login-url-to-content-iframe>>
<<validate-authentication>>
<<set-usage-in-iframe>>
<<get-all-disciplines-in-combobox>>
<<load-all-disciplines>>
<<load-all-institutes>>
<<load-all-labs>>
<<get-all-institutes>>
<<get-all-disciplines>>
<<get-all-labs>>
<<mouse-over>>
<<back-button>>
<<workshop-usage-data>>
<<total-usage-data>>
<<validate-cookie>>
<<validate-post-message>>
#+END_SRC

