#+TITLE: Institutes
#+AUTHOR: VLEAD
#+DATE: <2017-04-06 Thu>
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction
  This has functionality all the operations related to
  =Institute= entity =vlabs-landing-pages=
* Institutes
** Load all institutes
   This function loads all the institutes into
   =contentIframe= and before does this it removes existing
   =contentIframe= and creates new one

#+NAME:load-all-institutes
#+BEGIN_SRC javascript 
var loadAllInstitutes = function() {
  console.log("=======loading all institutes=====");
  deleteFrameInDivision("contentIframe", "contentDiv");
  var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "790em");
  insertFrameInDivision(newFrame, "contentDiv");
  getAllInstitutes();
};

#+END_SRC

** Get All Institutes   
   All the institutes from the =LDS= are collected along
   with images, hyperlinks.  This data is formatted and
   events are attached.  A div element is created containing
   this data.  The events attached are =onclick= and the
   handler loads the labs associated with the institute.
   This event =onclick= is attached for both the image and
   name of the institute.  Once the content is created,
   there is a call to insert this content in an iframe.

#+NAME: get-all-institutes
#+BEGIN_SRC javascript 
var getAllInstitutes = function(){ 
  console.log("=========inside get all institutes==========");
  var institute_url = lds_url+"/institutes";
//  console.log(institute_url);
  $.getJSON(institute_url, function(data) {
    var institutes = '';
    $.each(data, function(key, value){
      var institute_name = value['institute_name'];
      var image_name = value['assets'][0]['path'];
      var image_path = institute_images_url + image_name;

institutes += '<div class="col-lg-3 col-md-4 col-xs-12 thumb" \
 onclick="getLabsByInstituteName(this, 0)" src="' + image_path +'" id="' + institute_name +
      '"><div class="thumbnail" \
style="cursor:pointer; padding: 0px !important; padding-top:15px \
!important;"> <a><img class="img-responsive " \
onclick="getLabsByInstituteName(this, 0)" src="' + image_path +'" id="' + institute_name +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="getLabsByInstituteName(this, 0)"  src="' + image_path +'" id="' + institute_name +
      '" style="text-align:center; color:#2c99ce;" >'+ institute_name +'</h4></a></div></div></div>';
          });

    var institute_list = '<div class="container-fluid"><div class="row">'
        + institutes +'</div></div>';
//    console.log(institutes);
    setContent(institute_list, "institutes.html");
//    setNewContentInIframe(institute_list);
//    addScriptTags();
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC
** Get Labs by Institute Name
   This function gets the labs of respective institute based
   on the value of =click= event occurs on institute name.

#+NAME: get-labs-by-institute-name
#+BEGIN_SRC javascript 
var getLabsByInstituteName = function(image, flag) {
  console.log("===========inside getLabsByDisciplineName==========");
  if (flag==1){
    deleteFrameInDivision("contentIframe", "contentDiv");
    var newFrame = createNewIframe("contentIframe", "contentIframe", "100%", "650em");
    insertFrameInDivision(newFrame, "contentDiv");
  }
  var institute_name = image.id;
  var labs_url = lds_url+"/labs";
  var labs_by_institute_url = labs_url+"?institute_name="+ institute_name;
  console.log(labs_by_institute_url);
  $.getJSON(labs_by_institute_url, function(data) {
    var labs = '';
    $.each(data, function(key, value){
      var lab_name = value['lab_name'];
      var hosting_info = value['hosting_info'];
      for(var i=0;i< hosting_info.length;i++){
        var hosted_on = value['hosting_info'][i]['hosted_on'];
        if (hosting_info.length == 1){
          var hosted_url = value['hosting_info'][0]['hosted_url'];
        }
        else if(labs_hosted_platform == hosted_on)
        {
          hosted_url = value['hosting_info'][i]['hosted_url'];
        }
        else
        {
          continue;
        }
        
      }
      var assets = value['assets'];
      for(var i=0;i< assets.length;i++){
        var  asset_type = value['assets'][i]['asset_type']['asset_type'];
        var path = value['assets'][i]['path'];
        if (asset_type == 'image'){
          var image_name = value['assets'][i]['path'];
          path = lab_images_url + image_name;
        }
      }
      labs += '<div class=" col-md-3 " id='+ lab_name +
           '> <div class="thumbnail" style="cursor:pointer; padding: 0px !important;"><a><img class="img-responsive " \
onclick="javascript:validateAuthentication(this)" src="' + path +'" id="' + hosted_url +
      '"><div class="caption" style="min-height: 110px;">\
<h4 onclick="javascript:validateAuthentication(this)"  src="' + path +'" id="' + hosted_url +
      '" style="text-align:center; color:#2c99ce;" >'+ lab_name +'</h4></a></div></div></div>';

    });
//    console.log(labs);

    var labs_list = '<div class="container-fluid"><div class="row">'+ labs +'</div></div>';
    setContent(labs_list, "labs.html");
//    resetContentInIframe(labs);
  })
  .done(function() {
     console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
//      location.reload();
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC

** Get All Institutes in drop down menu
   This function does the following
   1. Gets all the institutes in drop down menu
   2. Display all the labs into =contentIframe= of chosen
      institute from drop down menu

#+NAME: get-all-institutes-in-combobox
#+BEGIN_SRC javascript
var getAllInstitutesInCombobox = function(){
  console.log("=========inside get all institutes in combobox==========");
  var institute_url = lds_url+"/institutes";
//  console.log(institute_url);
  $.getJSON(institute_url, function(data) {
    var institutes = '';
    $.each(data, function(key, value){
      var institute_name = value['institute_name'];
      institutes +=  '<li onclick="getLabsByInstituteName(this, 1)" value="'
        + institute_name + '" id="' + institute_name + '"><a >' +
        institute_name + '</a></li>';
    });
    var institute_list = '<li onclick="loadAllInstitutes()">\
<a >All Institutes</a></li>' + institutes;
//    console.log(institute_list);
    $('.filterInstituteComboBox').append(institute_list);
  })
    .done(function() {
//      console.log( "second success" );
    })
    .fail(function() {
//      console.log( "error" );
    })
    .always(function() {
//      console.log( "complete" );
    });
};

#+END_SRC
* Tangle 
** sources
*** Javascript
**** Main JS
#+BEGIN_SRC javascript :tangle js/institutes.js :eval no :noweb yes 
<<get-all-institutes-in-combobox>>
<<get-labs-by-institute-name>>
<<load-all-institutes>>
<<get-all-institutes>>
#+END_SRC
