#+TITLE: Vlabs Landing Pages
#+AUTHOR: VLEAD
#+DATE: [2017-05-03 Wednesday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This document describes  the design of =vlabs-landing-pages=.

* Design
  :PROPERTIES:
  :CUSTOM_ID: design
  :END: 
  
  Landing page will be divided into 3 frames.
  1) Header Iframe 
  2) Content Iframe
  3) Footer Iframe
** Header Iframe 
   On click of header tabs like institutes, disciplines and
   labs it has to load the data of institutes, disciplines
   and labs dynamically in content iframe. On Click of any
   loaded data like list of institutes, disciplines or labs
   it has to call a function such that it loads all labs in
   institutes, disciplines, labs respectively. once the list
   of labs are displayed users can access based on their
   choice.

** Content Iframe
   When the state changes, all the user actions will be loaded into the body Iframe. 
** Footer Iframe
   Footer will be served from footer service and will be loaded into footer
   iframe of vlabs landing page.
