#+TITLE: Vlabs Landing Pages
#+AUTHOR: VLEAD
#+DATE: [2017-04-03 Monday]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction 
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END: 
  This document describes all the requirements of =vlabs-landing-pages=.

* Requirements
  :PROPERTIES:
  :CUSTOM_ID: requirements
  :END: 

** Requirement 1
   Dynamically build Vlabs landing pages by fetching data
   from [[https://github.com/vlead/lab-data-service][lab data service]].

** Requirement 2
   Build a header service

** Requirement 3
   Build a search facility for the labs. 
   
** Requirement 4
   Building a login page with two iframes in it, one with the header part and the 
   other with the actual login page. This should be done by manipulating iframes.
   After log in, we should parse the source code of the iframe for a success 
   string. if login is successful, set the iframe's source to NULL and 
   populate the iframe dynamically with our custom HTML.
** Requirement 5
   After logging in, the user should be able to view the courses taken by 
   him/her. This should be dynamically done by getting data from LDS. 
   
** Requirement 6
   Building a login page with two iframes in it. This should be done by 
   manipulating iframes. If login is successful, the service inside the 
   iframe sends a success message to the parent service. This is implemented
   using post messages.
