#+TITLE: Demonstration Script for Virtual Labs Portal
#+AUTHOR: VLEAD
#+DATE: [2017-11-22 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ../org-templates/level-1.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate

* Introduction 
  This document lists steps to demonstrate various features
  of Virtual Labs portal using a beta version.

* Key Points
  1. Virtual Labs Portal is built dynamically by pulling
     data from multiple services - lab data service,
     analytics service, feedback service, outreach service,
     etc.
  2. Each lab is integrated seamlessly into the portal. 
  3. Search functionality provides a mechanism to search by
     words contained in the lab name.
  4. Single sign in for both Open edX and non Open edX labs
     is provided.  This allows provision to display total
     number of registered users and total number of active
     sessions.

* Note
  Please note that during the entire demonstration, back
  button should not be used.  The team is working on fixing
  this issue.

* Demonstration
  The demonstration is broken down into various scenarios.
  The focus of this demonstration will be on listing
  disciplines, listing institutes, listing all labs, listing
  labs of a discipline, listing labs of an institute and
  finally visiting a particular lab that will require sign
  in.

** Disciplines
   1. Click [[http://beta.vlabs.ac.in][here]] ([[http://beta.vlabs.ac.in]]) to load the beta version of Virtual Labs
      portal.
   2. The first page lists all the disciplines.
   3. Click on =Aerospace Engineering= to list the labs in
      that discipline.
   4. From the top Menu, choose =Disciplines= which will
      drop a menu down.  Choose =All Disciplines= to list
      all the disciplines.
   5. Click on =Computer Science and Engineering= to list the labs in
      that discipline.
   6. From the top Menu, choose =Disciplines= which will
      drop a menu down.  Choose =Electricial Engineering= to
      list all the labs of that discipline.

** Institutes
   1. From the top Menu, choose =Institutes= which will
      drop a menu down.  Choose =All Institutes= to list
      all the institutes.
   2. Click on =Amrita University= to list the labs in
      that institute.
   3. From the top Menu, choose =Institutes= which will
      drop a menu down.  Choose =IIT Delhi= to list
      all the labs of that institute.
   4. From the top Menu, choose =Institutes= which will
      drop a menu down.  Choose =IIIT Hyderabad= to list
      all the labs of that institute.

** All Labs
   1. From the top Menu, click on =All Labs= which
      will list all the labs.

** Search and Sign In
   1. Type the word =computer= in the search box situated at
      top right half of the page. As the word is being
      typed, the labs whose name matches the keyword are
      listed.
   2. Click on =Computer Programming= lab to open the lab.
   3. This will require sign in.  Enter the below
      credentials to login.
      + Email: vlabs-demo@vlabs.ac.in
      + Password: vlead123
   4. Click on =ENROLL IN CSE02= to enroll. 
   5. Click on =VIEW COURSE= to view the course.
   6. Click on the tab =Course= to view various experiments.
   7. Click on =Numerical Approximation= to view the experiment.
   8. Click on =Simulation= to perform the experiment.
   9. Click on =Full Screen= to conduct the experiment.
   10. Enter =5= for value of a, and =10= for value of b and
       click =ok=.
   11. Click =start= and later =next= to complete the experiment.
   12. Close the tab.
** Go back to Landing Page
   1. From the top Menu, choose =Disciplines= which will
      drop a menu down.  Choose =All Disciplines= to list
      all the disciplines.  This will end the
      demonstration. 

